-- CREATE SAMPLE 1 TABLE
CREATE TABLE TATILLA.SAMPLE1
(
	SAMPLE1_ID NUMBER(10) NOT NULL,
	STRING_VALUE_NOTNULL NVARCHAR2(50) NOT NULL,
    STRING_VALUE_NULL NVARCHAR2(50) NULL,
    NUMBER_VALUE_NOTNULL NUMBER NOT NULL,
    NUMBER_VALUE_NULL NUMBER NULL,
    CONSTRAINT SAMPLE1_ID_PK PRIMARY KEY (SAMPLE1_ID)
);
--INSERT SAMPLE DATA TO SAMPLE 1 TABLE
INSERT ALL
INTO TATILLA.SAMPLE1 (SAMPLE1_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL)
VALUES (1, 'SAMPLE1_VALUE_NOTNULL_1', NULL, 1, NULL)
INTO TATILLA.SAMPLE1 (SAMPLE1_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL)
VALUES (2, 'SAMPLE1_VALUE_NOTNULL_2', 'SAMPLE1_VALUE_NULL_2', 2, NULL)
INTO TATILLA.SAMPLE1 (SAMPLE1_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL)
VALUES (3, 'SAMPLE1_VALUE_NOTNULL_3', 'SAMPLE1_VALUE_NULL_3', 3, 3)
INTO TATILLA.SAMPLE1 (SAMPLE1_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL)
VALUES (4, ' ', NULL, 4, NULL)
SELECT * FROM DUAL;


-- CREATE SAMPLE 2 TABLE
CREATE TABLE TATILLA.SAMPLE2
(
	SAMPLE2_ID NUMBER(10) NOT NULL,
	STRING_VALUE_NOTNULL VARCHAR2(50) NOT NULL,
    STRING_VALUE_NULL VARCHAR2(50) NULL,
    NUMBER_VALUE_NOTNULL NUMBER NOT NULL,
    NUMBER_VALUE_NULL NUMBER NULL,
    CONSTRAINT SAMPLE2_ID_PK PRIMARY KEY (SAMPLE2_ID)
);
--INSERT SAMPLE DATA TO SAMPLE 2 TABLE
INSERT ALL
INTO TATILLA.SAMPLE2 (SAMPLE2_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL)
VALUES (1, 'SAMPLE2_VALUE_NOTNULL_1', NULL, 1, NULL)
INTO TATILLA.SAMPLE2 (SAMPLE2_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL)
VALUES (2, 'SAMPLE2_VALUE_NOTNULL_2', 'SAMPLE2_VALUE_NULL_2', 2, NULL)
INTO TATILLA.SAMPLE2 (SAMPLE2_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL)
VALUES (3, 'SAMPLE2_VALUE_NOTNULL_3', 'SAMPLE2_VALUE_NULL_3', 3, 3)
INTO TATILLA.SAMPLE2 (SAMPLE2_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL)
VALUES (4, ' ', NULL, 4, NULL)
SELECT * FROM DUAL;



-- CREATE SAMPLE 3 TABLE
CREATE TABLE TATILLA.SAMPLE3
(
	SAMPLE3_ID NUMBER(10) NOT NULL,
	STRING_VALUE_NOTNULL VARCHAR2(50) NOT NULL,
    STRING_VALUE_NULL VARCHAR2(50) NULL,
    NUMBER_VALUE_NOTNULL NUMBER NOT NULL,
    NUMBER_VALUE_NULL NUMBER NULL,
    SAMPLE1_ID NUMBER(10) NULL,
    SAMPLE2_ID NUMBER(10) NULL,
    CONSTRAINT SAMPLE3_ID_PK PRIMARY KEY (SAMPLE3_ID),
    CONSTRAINT SAMPLE1_ID_FK FOREIGN KEY (SAMPLE1_ID) REFERENCES TATILLA.SAMPLE1(SAMPLE1_ID),
    CONSTRAINT SAMPLE2_ID_FK FOREIGN KEY (SAMPLE2_ID) REFERENCES TATILLA.SAMPLE2(SAMPLE2_ID)
);

--INSERT SAMPLE DATA TO SAMPLE 3 TABLE
INSERT ALL
 INTO TATILLA.SAMPLE3 (SAMPLE3_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL, SAMPLE1_ID, SAMPLE2_ID)
VALUES (1, 'SAMPLE3_VALUE_NOTNULL_1', NULL, 1, NULL, NULL, NULL)
 INTO TATILLA.SAMPLE3 (SAMPLE3_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL, SAMPLE1_ID, SAMPLE2_ID)
VALUES (2, 'SAMPLE3_VALUE_NOTNULL_2', 'SAMPLE2_VALUE_NULL_2', 2, NULL, 1, NULL)
 INTO TATILLA.SAMPLE3 (SAMPLE3_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL, SAMPLE1_ID, SAMPLE2_ID)
VALUES (3, 'SAMPLE3_VALUE_NOTNULL_3', 'SAMPLE2_VALUE_NULL_3', 3, 3, 1,1)
 INTO TATILLA.SAMPLE3 (SAMPLE3_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL, SAMPLE1_ID, SAMPLE2_ID)
VALUES (4, ' ', NULL, 4, NULL, 1,1)
SELECT * FROM DUAL;



DECLARE
ID_INDEX NUMBER(10) := 4;
BEGIN
    FOR COUNTER_1 IN 1..4
    LOOP
        FOR COUNTER_2 IN 1..4
        LOOP
        	IF COUNTER_2 = 1 THEN
            	ID_INDEX := ID_INDEX + 1;
                    INSERT
                    INTO TATILLA.SAMPLE3 (SAMPLE3_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL, SAMPLE1_ID, SAMPLE2_ID)
                    VALUES (ID_INDEX, 'SAMPLE2_VALUE_NOTNULL_' || ID_INDEX , NULL, 1, NULL, NULL, COUNTER_2);
 			END IF;
              ID_INDEX := ID_INDEX + 1;
              INSERT
                    INTO TATILLA.SAMPLE3 (SAMPLE3_ID, STRING_VALUE_NOTNULL, STRING_VALUE_NULL, NUMBER_VALUE_NOTNULL, NUMBER_VALUE_NULL, SAMPLE1_ID, SAMPLE2_ID)
                    VALUES (ID_INDEX, 'SAMPLE2_VALUE_NOTNULL_' || ID_INDEX , NULL, 1, NULL, COUNTER_1, COUNTER_2);
        END LOOP;
    END LOOP;
END;

CREATE OR REPLACE PACKAGE TATILLA.PCK_APIQUERY AS 
-- 1. RETURN SINGLE VALUE
FUNCTION INSERT_SAMPLE1 
		(STRING_VALUE_NOTNULL VARCHAR2, 
        STRING_VALUE_NULL VARCHAR2, 
        NUMBER_VALUE_NOTNULL NUMBER, 
        NUMBER_VALUE_NULL NUMBER
        ) RETURN NUMBER;
     
-- 2. RETURN MULTIPLE VALUES
PROCEDURE GET_OBJECT 
        (PI_SAMPLE1_ID IN NUMBER, 
        PO_STRING_VALUE_NOTNULL OUT VARCHAR2, 
        PO_NUMBER_VALUE_NOTNULL OUT NUMBER
        );
-- 3. RETURN DATASET
PROCEDURE SINGLE_LIST
        (PI_SAMPLE1_ID IN NUMBER, 
        PO_DATASET      OUT SYS_REFCURSOR
        );
-- 4. RETURN MULTI DATASET
PROCEDURE MULTI_LIST
        (PI_SAMPLE1_ID IN NUMBER, 
        PO_DATASET      OUT SYS_REFCURSOR,
        PO_DATASET2      OUT SYS_REFCURSOR
        );
-- 5. RETURN MULTI VALUES AND MULTI DATASET

PROCEDURE COMPLEX_OBJECT
        (PI_DATA IN NUMBER, 
        PO_SAMPLE1_ID OUT NUMBER,
        PO_1ROW_LIST     OUT SYS_REFCURSOR,
        PO_MULTIROW_LIST   OUT SYS_REFCURSOR
        );

END PCK_APIQUERY;
/


CREATE OR REPLACE PACKAGE BODY TATILLA.PCK_APIQUERY
AS
   -- 1. RETURN SINGLE VALUE
   FUNCTION INSERT_SAMPLE1 (STRING_VALUE_NOTNULL    VARCHAR2,
                            STRING_VALUE_NULL       VARCHAR2,
                            NUMBER_VALUE_NOTNULL    NUMBER,
                            NUMBER_VALUE_NULL       NUMBER)
      RETURN NUMBER
   IS
      V_PI_SAMPLE1_ID   NUMBER;
   BEGIN
      SELECT MAX (SAMPLE1_ID)+1 INTO V_PI_SAMPLE1_ID FROM TATILLA.SAMPLE1;


      INSERT INTO TATILLA.SAMPLE1 (SAMPLE1_ID,
                                   STRING_VALUE_NOTNULL,
                                   STRING_VALUE_NULL,
                                   NUMBER_VALUE_NOTNULL,
                                   NUMBER_VALUE_NULL)
          VALUES (V_PI_SAMPLE1_ID,
                  STRING_VALUE_NOTNULL,
                  STRING_VALUE_NULL,
                  NUMBER_VALUE_NOTNULL,
                  NUMBER_VALUE_NULL);

      RETURN (V_PI_SAMPLE1_ID);
   END;


   -- 2. RETURN MULTIPLE VALUES
   PROCEDURE GET_OBJECT (PI_SAMPLE1_ID             IN     NUMBER,
                          PO_STRING_VALUE_NOTNULL      OUT VARCHAR2,
                          PO_NUMBER_VALUE_NOTNULL      OUT NUMBER)
   IS
   BEGIN
      SELECT S.STRING_VALUE_NOTNULL, S.NUMBER_VALUE_NOTNULL
        INTO PO_STRING_VALUE_NOTNULL, PO_NUMBER_VALUE_NOTNULL
        FROM TATILLA.SAMPLE1 S
       WHERE S.SAMPLE1_ID = PI_SAMPLE1_ID;
   END GET_OBJECT;

   -- 3. RETURN DATASET
   PROCEDURE SINGLE_LIST (PI_SAMPLE1_ID   IN     NUMBER,
                                     PO_DATASET         OUT SYS_REFCURSOR)
   IS
   BEGIN
      OPEN PO_DATASET FOR
         SELECT SAMPLE3_ID,
                STRING_VALUE_NOTNULL,
                STRING_VALUE_NULL,
                NUMBER_VALUE_NOTNULL,
                NUMBER_VALUE_NULL,
                SAMPLE1_ID,
                SAMPLE2_ID
           FROM TATILLA.SAMPLE3 S
          WHERE S.SAMPLE1_ID = PI_SAMPLE1_ID;
   END SINGLE_LIST;

   -- 4. RETURN MULTI DATASET


   PROCEDURE MULTI_LIST (PI_SAMPLE1_ID   IN     NUMBER,
                                      PO_DATASET         OUT SYS_REFCURSOR,
                                      PO_DATASET2        OUT SYS_REFCURSOR)
   IS
   BEGIN
      OPEN PO_DATASET FOR
         SELECT SAMPLE3_ID,
                STRING_VALUE_NOTNULL,
                STRING_VALUE_NULL,
                NUMBER_VALUE_NOTNULL,
                NUMBER_VALUE_NULL,
                SAMPLE1_ID,
                SAMPLE2_ID
           FROM TATILLA.SAMPLE3 S
          WHERE S.SAMPLE1_ID = PI_SAMPLE1_ID;

      OPEN PO_DATASET2 FOR
         SELECT SAMPLE3_ID,
                STRING_VALUE_NOTNULL,
                STRING_VALUE_NULL,
                NUMBER_VALUE_NOTNULL,
                NUMBER_VALUE_NULL,
                SAMPLE1_ID,
                SAMPLE2_ID
           FROM TATILLA.SAMPLE3 S
          WHERE S.SAMPLE1_ID = PI_SAMPLE1_ID;
   END MULTI_LIST;

   PROCEDURE COMPLEX_OBJECT (PI_DATA     IN     NUMBER,
                                PO_SAMPLE1_ID         OUT NUMBER,
                                PO_1ROW_LIST          OUT SYS_REFCURSOR,
                                PO_MULTIROW_LIST      OUT SYS_REFCURSOR)
   IS
   BEGIN
   
   SELECT SAMPLE1_ID INTO PO_SAMPLE1_ID FROM TATILLA.SAMPLE3
   WHERE SAMPLE3_ID=PI_DATA;
   
      OPEN PO_1ROW_LIST FOR
         SELECT SAMPLE3_ID,
                STRING_VALUE_NOTNULL,
                STRING_VALUE_NULL,
                NUMBER_VALUE_NOTNULL,
                NUMBER_VALUE_NULL,
                SAMPLE1_ID,
                SAMPLE2_ID
           FROM TATILLA.SAMPLE3 S
          WHERE S.SAMPLE3_ID = PI_DATA
           AND ROWNUM=1;

      OPEN PO_MULTIROW_LIST FOR
         SELECT SAMPLE3_ID,
                STRING_VALUE_NOTNULL,
                STRING_VALUE_NULL,
                NUMBER_VALUE_NOTNULL,
                NUMBER_VALUE_NULL,
                SAMPLE1_ID,
                SAMPLE2_ID
           FROM TATILLA.SAMPLE3 S
          WHERE S.SAMPLE1_ID = PI_DATA;
   END COMPLEX_OBJECT;
-- 5. RETURN MULTI VALUES AND MULTI DATASET


END PCK_APIQUERY;
/

